import pymannkendall as pk
import pandas as pd
#df = pd.read_excel(r"I:\GPM\May_2001-2020_monthly\maytimeseries.xlsx",sheet_name="Sheet1",usecols="R:AE")
#df = pd.read_excel(r"F:\AOD_ANALYSIS\MERRA_2\Monthly\timeseries\March\ALL_Location_March.xlsx",sheet_name="Sheet1",usecols="B:P")
#df = pd.read_excel(r"F:\AOD_ANALYSIS\MODIS_MOD_L3\MOD08_L3.xlsx",sheet_name="REGION1",usecols="B:N",nrows=21)
#df = pd.read_excel(r"F:\GPM.xlsx",sheet_name="Sheet1",usecols="B:M",nrows=566)
df = pd.read_excel(r"F:\GPM_ANALYSIS\timeseries\monthly\region1\GPM_timeseries_REGION1.xlsx",sheet_name="MAR",usecols="B:M",nrows=21)
#print(df)
'''
result = pk.original_test(df["GUWAHATI"])
print(result)
result = pk.original_test(df["dibrugarh"])
print(result)
result = pk.original_test(df["agartala"])
print(result)
result = pk.original_test(df["tezpur"])
print(result)
result = pk.original_test(df["silchar"])
print(result)
result = pk.original_test(df["bongaigaon"])
print(result)
result = pk.original_test(df["aizawl"])
print(result)
result = pk.original_test(df["kohima"])
print(result)
result = pk.original_test(df["jorhat"])
print(result)
result = pk.original_test(df["imphal"])
print(result)
result = pk.original_test(df["dhuburi"])
print(result)
result = pk.original_test(df["dhaka"])
print(result)
result = pk.original_test(df["shillong"])
print(result)
result = pk.original_test(df["pasighat"])
print(result)
'''
'''
result = pk.hamed_rao_modification_test(df["AGARTALA"],lag=20)
print(result)
result = pk.hamed_rao_modification_test(df["AIZAWL"])
print(result)
result = pk.hamed_rao_modification_test(df["BONGAIGAON"])
print(result)
result = pk.hamed_rao_modification_test(df["DHAKA"])
print(result)
result = pk.hamed_rao_modification_test(df["DHUBURI"])
print(result)
result = pk.hamed_rao_modification_test(df["DIBRUGARH"])
print(result)
result = pk.hamed_rao_modification_test(df["GUWAHATI"])
print(result)
result = pk.hamed_rao_modification_test(df["IMPHAL"])
print(result)
result = pk.hamed_rao_modification_test(df["JORHAT"])
print(result)
result = pk.hamed_rao_modification_test(df["KOHIMA"])
print(result)
result = pk.hamed_rao_modification_test(df["PASIGHAT"])
print(result)
result = pk.hamed_rao_modification_test(df["SHILLONG"])
print(result)
result = pk.hamed_rao_modification_test(df["SILCHAR"])
print(result)
result = pk.hamed_rao_modification_test(df["TEZPUR"])
print(result)
result = pk.hamed_rao_modification_test(df["ALL_LOCATION"])
print(result)
'''
'''
result = pk.hamed_rao_modification_test(df["JAN"])
print(result)
result = pk.hamed_rao_modification_test(df["FEB"])
print(result)
result = pk.hamed_rao_modification_test(df["MAR"])
print(result)
result = pk.hamed_rao_modification_test(df["APR"])
print(result)
result = pk.hamed_rao_modification_test(df["MAY"])
print(result)
result = pk.hamed_rao_modification_test(df["JUN"])
print(result)
result = pk.hamed_rao_modification_test(df["JUL"])
print(result)
result = pk.hamed_rao_modification_test(df["AUG"])
print(result)
result = pk.hamed_rao_modification_test(df["SEP"])
print(result)
result = pk.hamed_rao_modification_test(df["OCT"])
print(result)
result = pk.hamed_rao_modification_test(df["NOV"])
print(result)
result = pk.hamed_rao_modification_test(df["DEC"])
print(result)
result = pk.hamed_rao_modification_test(df["MEAN"])
print(result)
'''
'''
result = pk.hamed_rao_modification_test(df["JAN"])
print(result)
result = pk.hamed_rao_modification_test(df["FEB"])
print(result)
result = pk.hamed_rao_modification_test(df["MAR"])
print(result)
result = pk.hamed_rao_modification_test(df["APR"])
print(result)
result = pk.hamed_rao_modification_test(df["MAY"])
print(result)
result = pk.hamed_rao_modification_test(df["JUN"])
print(result)
result = pk.hamed_rao_modification_test(df["JUL"])
print(result)
result = pk.hamed_rao_modification_test(df["AUG"])
print(result)
result = pk.hamed_rao_modification_test(df["SEP"])
print(result)
result = pk.hamed_rao_modification_test(df["OCT"])
print(result)
result = pk.hamed_rao_modification_test(df["NOV"])
print(result)
result = pk.hamed_rao_modification_test(df["DEC"])
print(result)
#result = pk.hamed_rao_modification_test(df["MEAN"])
#print(result)
'''
'''
result = pk.yue_wang_modification_test(df["AOD"])
print(result)
'''
print(df['COOCHBEHAR'])
result = pk.original_test(df["COOCHBEHAR"])
print(result)
result = pk.original_test(df["RANGPUR"])
print(result)
result = pk.original_test(df["KOKRAJHAR"])
print(result)
result = pk.original_test(df["BONGAIGAON"])
print(result)
result = pk.original_test(df["GOALPARA"])
print(result)
result = pk.original_test(df["BARPETA"])
print(result)
result = pk.original_test(df["NALBARI"])
print(result)
result = pk.original_test(df["GUWAHATI"])
print(result)
result = pk.original_test(df["MAWSYNRAM"])
print(result)
result = pk.original_test(df["SHILLONG"])
print(result)
result = pk.original_test(df["DHUBURI"])
print(result)
result = pk.original_test(df["SUM"])
print(result)
