import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.patches as mpatch

#ds = pd.read_excel(r"D:\PHD\My PhD Reports\Manuscripts\New.xlsx", sheet_name="WIND_DIR",usecols="Q:AD")
'''
print(ds)
plt.figure(figsize=(5.5,8))
plt.plot(ds["RADIOSONDE.1"],ds["RADIOSONDE_HGT.1"],color='magenta',linestyle="--")
#plt.plot(ds["RADIOSONDE"],ds["PH"],color='magenta',linestyle="--")
plt.plot(ds["ACM2.1"],ds["PH1.1"],color='dodgerblue')
plt.plot(ds["HONG.1"],ds["PH2.1"],color='coral')
plt.plot(ds["MYJ.1"],ds["PH3.1"],color='gold')
plt.plot(ds["MYNN3.1"],ds["PH4.1"],color='lime')
plt.plot(ds["QNSE.1"],ds["PH5.1"],color='aqua')
plt.plot(ds["YSU.1"],ds["PH6.1"],color='grey')
plt.ylim(0,5000)
plt.xticks(None)
#plt.axvline(x=0,color="black",linestyle="--")
magenta = mpatch.Patch(color="magenta", label="Observed")
blue = mpatch.Patch(color="dodgerblue", label="ACM2")
coral = mpatch.Patch(color="coral", label="HONG")
gold = mpatch.Patch(color="gold", label="MYJ")
chocolate = mpatch.Patch(color="lime", label="MYNN3")
aqua = mpatch.Patch(color="aqua", label="QNSE")
yellow = mpatch.Patch(color="grey", label="YSU")
plt.legend(handles=[magenta,blue,coral,gold,chocolate,aqua,yellow])
plt.ylabel("Height (m)")
plt.xlabel("Relative humidity (%)")
plt.xlim(0,360)
#plt.title("(a) April")
plt.title("(b) July")
#plt.savefig("Monsoon RH.png",dpi=300,bbox_inches='tight')
plt.show()
'''
'''
ds = pd.read_excel(r"F:\WRF\WRF_lower_atmosphere_analysis\wholeday analysis\APRIL\W_April.xlsx", sheet_name="GUW",usecols="A:L",skiprows=22)
#ds = pd.read_excel(r"F:\WRF\WRF_lower_atmosphere_analysis\wholeday analysis\JULY\W.xlsx", sheet_name="GUW",usecols="N:Y",skiprows=0)
plt.figure(figsize=(5.5,8))
#plt.plot(ds["RADIOSONDE.1"],ds["RADIOSONDE_HGT.1"],color='magenta',linestyle="--")
#plt.plot(ds["RADIOSONDE"],ds["PH"],color='magenta',linestyle="--")
plt.plot(ds["ACM2"],ds["GPH"],color='dodgerblue')
plt.plot(ds["HONG"],ds["GPH"],color='coral')
plt.plot(ds["MYJ"],ds["GPH"],color='gold')
plt.plot(ds["MYNN3"],ds["GPH"],color='lime')
plt.plot(ds["QNSE"],ds["GPH"],color='aqua')
plt.plot(ds["YSU"],ds["GPH"],color='grey')
plt.ylim(0,1500)
plt.xticks(None)
#plt.axvline(x=0,color="black",linestyle="--")
#magenta = mpatch.Patch(color="magenta", label="Observed")
blue = mpatch.Patch(color="dodgerblue", label="ACM2")
coral = mpatch.Patch(color="coral", label="HONG")
gold = mpatch.Patch(color="gold", label="MYJ")
chocolate = mpatch.Patch(color="lime", label="MYNN3")
aqua = mpatch.Patch(color="aqua", label="QNSE")
yellow = mpatch.Patch(color="grey", label="YSU")
plt.legend(handles=[blue,coral,gold,chocolate,aqua,yellow])
plt.ylabel("Height (m)")
plt.xlabel("Moist potential temperature (K)")
plt.xlim(304.5,310)
#plt.title("(a) April")
plt.title("(a) April")
plt.savefig("April moist pot tem.png",dpi=300,bbox_inches='tight')
plt.show()
'''

ds = pd.read_excel(r"F:\WRF-CHEM ANALYSIS\WRF level analysis\cldfra\cldfra and temp .xlsx", sheet_name="cldfra region",usecols="X:Y",skiprows=1)
#ds = pd.read_excel(r"F:\WRF-CHEM ANALYSIS\WRF level analysis\cldfra\cldfra and temp .xlsx", sheet_name="TEMP",usecols="Y:AC",skiprows=1)
#ds = pd.read_excel(r"F:\WRF\WRF_lower_atmosphere_analysis\wholeday analysis\JULY\W.xlsx", sheet_name="GUW",usecols="N:Y",skiprows=0)
plt.figure(figsize=(6,8))
#plt.plot(ds["RADIOSONDE.1"],ds["RADIOSONDE_HGT.1"],color='magenta',linestyle="--")
#plt.plot(ds["RADIOSONDE"],ds["PH"],color='magenta',linestyle="--")
print(ds.keys())
print(ds)
plt.plot(ds["NOR.4"],ds["Height.4"],color='dodgerblue')
#plt.plot(ds["2NOR-NO_BC_ABS.3"],ds["Height.3"],color='coral')
#plt.plot(ds["4NOR-NO_BC_ABS.3"],ds["Height.3"],color='gold')
#plt.plot(ds["NOR-NOFEED.3"],ds["Height.3"],color='lime')
#plt.plot(ds["NOR-NO_BC_ABS (without region4)"],ds["Height.4"],color='aqua')
#plt.plot(ds["2NOR-NO_BC_ABS (without region4)"],ds["Height.4"],color='grey')
#plt.plot(ds["4NOR-NO_BC_ABS (without region4)"],ds["Height.4"],color='black')
#plt.plot(ds["NOR-NOFEED (without region4)"],ds["Height.4"],color='magenta')
plt.ylim(0,16000)
plt.xticks(None)
#plt.axvline(x=0.00,color="black",linestyle="-")
#magenta = mpatch.Patch(color="magenta", label="Observed")
#blue = mpatch.Patch(color="dodgerblue", label="NOR-NO_BC_ABS")
#coral = mpatch.Patch(color="coral", label="2NOR-NO_BC_ABS")
#gold = mpatch.Patch(color="gold", label="4NOR-NO_BC_ABS")
#chocolate = mpatch.Patch(color="lime", label="NOR-NOFEED")

#aqua = mpatch.Patch(color="aqua", label="NOR-NO_BC_ABS (no region 4)")
#grey = mpatch.Patch(color="grey", label="2NOR-NO_BC_ABS (no region 4)")
#black = mpatch.Patch(color="black", label="4NOR-NO_BC_ABS (no region 4)")
#magenta = mpatch.Patch(color="magenta", label="NOR-NOFEED (no region 4)")
#aqua = mpatch.Patch(color="aqua", label="QNSE")
#yellow = mpatch.Patch(color="grey", label="YSU")
#plt.legend(handles=[blue])#,coral,gold,chocolate])#,aqua,grey,black,magenta])
plt.ylabel("Height (m)")
plt.xlabel("cloud fraction")
#plt.xlim(0.00,0.06)
#plt.title("(a) April")
#plt.title("(a) April")
plt.savefig('D:\PHD\My PhD Reports\Manuscript3\cldfra_VERTICAL PROFILE-region average.png',dpi=600,bbox_inches='tight')
plt.show()